### ISSUE TITLE
add manditory language tag in addon.xml

### ISSUE THREAD

**Issue by MartijnKaijser** [Giftie/script.cdartmanager#12]
Add  this to the metadata part in addon.xml
< language/ >

**Comment by Giftie** [comment]
Thanks for the notify..  Goes to show that the last version that was on the repo was before Eden was finalized..

**Comment by MartijnKaijser** [comment]
it's a Frodo requirement but already sales now

**Comment by MartijnKaijser** [comment]
sales=asked
