### ISSUE TITLE
!!! Killing the GPU processor !!!

### ISSUE THREAD

**Issue by bruvv** [Giftie/script.cdartmanager#18]
When I run xbmc in a window minimised:
![image](https://f.cloud.github.com/assets/3063928/157755/79b53eba-76cd-11e2-89b2-f8d9a19a35dc.png)

When I open it up, my whole pc becomes really REALY slow and my GPU core is maxed out and the tempature shoots sky high.
![image](https://f.cloud.github.com/assets/3063928/157758/a451f834-76cd-11e2-9afa-6147738849e1.png)

This realy need to have a look.

**Comment by Giftie** [comment]
Nothing can be done with in the script, it uses XBMC's GUI functions.
