### ISSUE TITLE
after library scan it still shows no artists or albums

### ISSUE THREAD

**Issue by Albinoman887** [Giftie/script.cdartmanager#9]
it goes through the scan sems like its working but then there still 0 artsts etc this is with latests git of xbmc and this

**Comment by Giftie** [comment]
Have you installed the latest version(2.5.1)?  Also I would need a copy of your debug log to figure out the problem

**Comment by Albinoman887** [comment]
Yes I have ill get u a log
On Oct 4, 2011 3:36 PM, "Giftie" <
reply@reply.github.com>
wrote:
